import { DsTypographyTokens } from '../Types'

export const DSTYPOGRAPHY_TOKENS: DsTypographyTokens[] = [
  'displayBoldLarge',
  'displayBoldMedium',
  'displayBoldSmall',
  'displayBoldItalicLarge',
  'displayBoldItalicMedium',
  'displayBoldItalicSmall',
  'headingBoldExtraLarge',
  'headingBoldLarge',
  'headingBoldMedium',
  'headingBoldSmall',
  'headingBoldExtraSmall',
  'subheadingSemiboldLarge',
  'subheadingSemiboldDefault',
  'headingBoldItalicExtraLarge',
  'headingBoldItalicLarge',
  'headingBoldItalicMedium',
  'headingBoldItalicSmall',
  'headingBoldItalicExtraSmall',
  'bodyRegularLarge',
  'bodyRegularMedium',
  'bodyRegularSmall',
  'bodyBoldLarge',
  'bodyBoldMedium',
  'bodyBoldSmall',
  'supportRegularInfo',
  'supportRegularFootnote',
  'supportBoldTextButton',
  'supportRegularMetadata'
]
