export default dsSpacing;
export const SPACE_COEFFICIENT: 4;
export namespace dsSpacingCssVars {
    const zero: number;
    const deepFreeze: number;
    const quickFreeze: number;
    const glacial: number;
    const frostbite: number;
    const bitterCold: number;
    const cool: number;
    const mild: number;
    const pleasant: number;
    const warm: number;
    const tepid: number;
    const tropical: number;
    const hot: number;
    const blazing: number;
    const molten: number;
    const superheated: number;
    const meltdown: number;
    const whiteHot: number;
    const plasma: number;
}
export function getSpacingPX(multiplier: any): string;
declare namespace dsSpacing {
    const zero_1: number;
    export { zero_1 as zero };
    const deepFreeze_1: number;
    export { deepFreeze_1 as deepFreeze };
    const quickFreeze_1: number;
    export { quickFreeze_1 as quickFreeze };
    const glacial_1: number;
    export { glacial_1 as glacial };
    const frostbite_1: number;
    export { frostbite_1 as frostbite };
    const bitterCold_1: number;
    export { bitterCold_1 as bitterCold };
    const cool_1: number;
    export { cool_1 as cool };
    const mild_1: number;
    export { mild_1 as mild };
    const pleasant_1: number;
    export { pleasant_1 as pleasant };
    const warm_1: number;
    export { warm_1 as warm };
    const tepid_1: number;
    export { tepid_1 as tepid };
    const tropical_1: number;
    export { tropical_1 as tropical };
    const hot_1: number;
    export { hot_1 as hot };
    const blazing_1: number;
    export { blazing_1 as blazing };
    const molten_1: number;
    export { molten_1 as molten };
    const superheated_1: number;
    export { superheated_1 as superheated };
    const meltdown_1: number;
    export { meltdown_1 as meltdown };
    const whiteHot_1: number;
    export { whiteHot_1 as whiteHot };
    const plasma_1: number;
    export { plasma_1 as plasma };
}
