export interface DsColor {
  actionPrimary: string
  actionSecondary: string
  actionTertiary: string
  surfaceBackground: string
  surfacePrimary: string
  surfaceSecondary: string
  surfaceTertiary: string
  typoPrimary: string
  typoSecondary: string
  typoTertiary: string
  typoActionPrimary: string
  typoActionSecondary: string
  typoActionTertiary: string
  typoOnSurface: string
  typoDisabled: string
  typoTypical: string
  neutral1: string
  neutral2: string
  neutral3: string
  neutral4: string
  neutral5: string
  neutral6: string
  iconSupportNegative: string
  iconSupportPositive: string
  iconSupportWarning: string
  iconActionPrimary: string
  iconActionSecondary: string
  iconActionTertiary: string
  iconOnSurface: string
  iconDisabled: string
  iconDefault: string
  iconTypical: string
  strokeDefault: string
  strokeSelected: string
  strokeSecondarySelected: string
  strokeHover: string
  strokeDisabled: string
  strokeActive: string
  supportNegative: string
  supportPositive: string
  supportWarning: string
  supportVariable: string
  supportTypical: string
  supportNegativeNeutral: string
  supportPositiveNeutral: string
  supportWarningNeutral: string
  supportTypicalNeutral: string
  stateSelectedPrimaryHover: string
  stateSelectedPrimaryPressed: string
  stateSelectedSecondaryHover: string
  stateSelectedSecondaryPressed: string
  stateSelectedVisitedTextLink: string
  stateUnselectedDefault: string
  stateUnselectedHover: string
  stateUnselectedPressed: string
  stateDisabledSurface: string
  overlay: string
  overlayLoader: string
}

export interface DsColorOverides {
  actionPrimary: true
  actionSecondary: true
  actionTertiary: true
  surfaceBackground: true
  surfacePrimary: true
  surfaceSecondary: true
  surfaceTertiary: true
  typoPrimary: true
  typoSecondary: true
  typoTertiary: true
  typoActionPrimary: true
  typoActionSecondary: true
  typoActionTertiary: true
  typoOnSurface: true
  typoDisabled: true
  typoTypical: true
  neutral1: true
  neutral2: true
  neutral3: true
  neutral4: true
  neutral5: true
  neutral6: true
  iconSupportNegative: true
  iconSupportPositive: true
  iconSupportWarning: true
  iconActionPrimary: true
  iconActionSecondary: true
  iconActionTertiary: true
  iconOnSurface: true
  iconDisabled: true
  iconDefault: true
  iconTypical: true
  strokeDefault: true
  strokeSelected: true
  strokeSecondarySelected: true
  strokeHover: true
  strokeDisabled: true
  strokeActive: true
  supportNegative: true
  supportPositive: true
  supportWarning: true
  supportVariable: true
  supportTypical: true
  supportNegativeNeutral: true
  supportPositiveNeutral: true
  supportWarningNeutral: true
  supportTypicalNeutral: true
  stateSelectedPrimaryHover: true
  stateSelectedPrimaryPressed: true
  stateSelectedSecondaryHover: true
  stateSelectedSecondaryPressed: true
  stateSelectedVisitedTextLink: true
  stateUnselectedDefault: true
  stateUnselectedHover: true
  stateUnselectedPressed: true
  stateDisabledSurface: true
  overlay: true
  overlayLoader: true
}

export interface DsColorClass {
  colorActionPrimary: string
  colorActionSecondary: string
  colorActionTertiary: string
  colorSurfaceBackground: string
  colorSurfacePrimary: string
  colorSurfaceSecondary: string
  colorSurfaceTertiary: string
  colorTypoPrimary: string
  colorTypoSecondary: string
  colorTypoTertiary: string
  colorTypoActionPrimary: string
  colorTypoActionSecondary: string
  colorTypoActionTertiary: string
  colorTypoOnSurface: string
  colorTypoDisabled: string
  colorTypoTypical: string
  colorNeutral1: string
  colorNeutral2: string
  colorNeutral3: string
  colorNeutral4: string
  colorNeutral5: string
  colorNeutral6: string
  colorIconSupportNegative: string
  colorIconSupportPositive: string
  colorIconSupportWarning: string
  colorIconActionPrimary: string
  colorIconActionSecondary: string
  colorIconActionTertiary: string
  colorIconOnSurface: string
  colorIconDisabled: string
  colorIconDefault: string
  colorIconTypical: string
  colorStrokeDefault: string
  colorStrokeSelected: string
  colorStrokeSecondarySelected: string
  colorStrokeHover: string
  colorStrokeDisabled: string
  colorStrokeActive: string
  colorSupportNegative: string
  colorSupportPositive: string
  colorSupportWarning: string
  colorSupportVariable: string
  colorSupportTypical: string
  colorSupportNegativeNeutral: string
  colorSupportPositiveNeutral: string
  colorSupportWarningNeutral: string
  colorSupportTypicalNeutral: string
  colorStateSelectedPrimaryHover: string
  colorStateSelectedPrimaryPressed: string
  colorStateSelectedSecondaryHover: string
  colorStateSelectedSecondaryPressed: string
  colorStateSelectedVisitedTextLink: string
  colorStateUnselectedDefault: string
  colorStateUnselectedHover: string
  colorStateUnselectedPressed: string
  colorStateDisabledSurface: string
  colorOverlay: string
  colorOverlayLoader: string
}
